name: PR Preview

on:
  - pull_request
  - workflow_dispatch

permissions:
  checks: write
  contents: read
  pull-requests: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build_drafts_on:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.147.9
    outputs:
      preview_url: ${{ steps.deploy.outputs.details_url }}
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Svelte components
        run: |
          # build all svelte components (in parallel)
          ./svelte/quick-check/build-quick-check.sh & \
          ./svelte/core-v2/build-core.sh & \
          ./svelte/experimental-ai-model/build-ai-model.sh & \
          wait
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo --source=./hugo --logLevel=debug --buildDrafts
      - name: Deploy to Firebase
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DORA_DEV_SANDBOX }}
          expires: 30d
          projectId: dora-dev-sandbox
          channelId: ${{ github.ref }}_drafts_on
  build_drafts_off:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.147.9
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Svelte components
        run: |
          # build all svelte components (in parallel)
          ./svelte/quick-check/build-quick-check.sh & \
          ./svelte/core-v2/build-core.sh & \
          ./svelte/experimental-ai-model/build-ai-model.sh & \
          wait
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo --source=./hugo --logLevel=debug
      - name: Deploy to Firebase
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DORA_DEV_SANDBOX }}
          expires: 30d
          projectId: dora-dev-sandbox
          channelId: ${{ github.ref }}_drafts_off
  # shard tests across multiple workers
  test:
    strategy:
      matrix:
        shard: [1, 2, 3, 4]
    runs-on: ubuntu-latest
    needs: build_drafts_on
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up playwright
        working-directory: test/playwright
        run: npm ci && npx playwright install --with-deps
      - name: Playwright tests
        working-directory: test/playwright
        env:
          PLAYWRIGHT_BASE_URL: ${{needs.build_drafts_on.outputs.preview_url}}
        run: |
          set -u
          npx playwright test --max-failures=1 --shard=${{ matrix.shard }}/${{ strategy.job-total }}
  
